### ISSUE TITLE
Other Metadata

### ISSUE THREAD

**Issue by balmy-gazebo** [wen-community/wen-new-standard#27]
Currently the program only allows for metadata to be added via Add Royalties functionality. We'd like to change it so that beyond creators, collections can add additional metadata, remove fields, and more.

Will need:
- Update meta IX that restricts over-writing creators and royalties amount
- Add/remove creators IX
- Update the distribution instruction to only search for creators when issuing payments
- Add validation to Add Royalties to ensure all creators are valid pub keys

There are some additional assumptions that will need to be made here, my gut says we can leave any key that is a Pubkey and safely assume it's a creator. This will eliminate most issues.

**Comment by L0STE** [comment]
I'm not sure about what should be changed in the 3rd point here, can you be a little more specific? 

Plus do you guys have a test folder so i don't have to build the test from scratch? I'm testing the implementation on my own of just the integration, so seeing if that works with the whole progran too might be nice

**Comment by L0STE** [comment]
**Preventing Overwrites on Creators and Royalties**

I assumed we should only allow public keys for the "Creators" field. To enforce this, I set up an add_metadata function. It checks if any fields passed are public keys and errors out if they are. This way, we ensure that the only way to add metadata (aside from royalty data) is through this controlled process, safeguarding against overwrites.

```rust
for metadata_arg in args {
    // Check if the field is a public key
    match Pubkey::from_str(&metadata_arg.field) {
        Ok(_) => {
            return Err(MetadataErrors::InvalidField.into());
        },
        Err(_) => {
            ctx.accounts.update_token_metadata_field(Field::Key(metadata_arg.field), metadata_arg.value.to_string())?;
        }
    }
}
```

**Updating Creators**

Instead of separate instructions for adding and removing creators, I took advantage of the way the update_metadata instruction works: it either creates a new field (if it doesn't exist) or updates an existing one. 

To remove creators, I used a combo of remove_key instruction and a custom check against the current metadata. If a creator isn't in the new list, we remove them.

```rust
// Identify and remove creators no longer needed
let keys_to_remove: Vec<String> = metadata
    .additional_metadata
    .iter()
    .filter_map(|(key, _)| match Pubkey::from_str(key) {
        Ok(pubkey) => {
            if !creators_arg.iter().any(|creator| creator.address == pubkey.to_string()) {
                Some(key.clone())
            } else {
                None
            }
        },
        Err(_) => None,
    })
    .collect();

for key in keys_to_remove {
    ctx.accounts.remove_token_metadata_field(key)?;
}
```

_Note: For the remove_key instruction I'm sticking with creating it raw for now. Let me know if you think we should add a macro for it in the BrisgeSplit Repo_

**Problem created by this instruction: Account Lamport Adjustments**
Ran into an issue where update_account_lamports_to_minimum_balance doesn't account for reductions in account space. I whipped up update_account_lamports_to_minimum_balance2 to handle cases where the space decreases. It attempts to refund lamports, but since the Mint needs to sign, this might not fly in production. Might need to include this check in all instructions since we could have this problem even if the instruction doesn't decrease the space in that exact instruction. 

**Updated the distribution instruction to only search for creators when issuing payments**
When distributing payments, I made sure we only consider valid creator public keys. Any invalid keys are ignored, simplifying the process.

```rust
.filter_map(|(key, value)| match Pubkey::from_str(key) {
    Ok(pubkey) => Some(CreatorShare {
        address: pubkey,
        pct: u8::from_str(value).unwrap(),
    }),
    Err(_) => None,
})
.collect::<Vec<CreatorShare>>();
```

**Add validation to Add Royalties to ensure all creators are valid pub keys**
Added a quick check to ensure all creators are valid public keys before adding royalties. This catches any invalid keys early on.

```rust
for creator in args.creators {
    // Ensure each creator has a valid public key
    match Pubkey::from_str(&creator.address) {
        Ok(_) => {
            total_share = total_share
            .checked_add(creator.share)
            .ok_or(MetadataErrors::CreatorShareInvalid)?;
            ctx.accounts
            .update_token_metadata_field(Field::Key(creator.address), creator.share.to_string())?;
        },
        Err(_) => return Err(MetadataErrors::CreatorAddressInvalid.into()),
    }
}
```

I also added a sanity check to make sure the royalty fee basis points don't exceed 10000, preventing future errors.

```rust
require!(args.royalty_basis_points <= 10000, MetadataErrors::RoyaltyBasisPointsInvalid);
```

**Conclusion**
Let me know your thoughts or if there's anything else i should tweak! I left the test folder to simplifying the process of testing the implementation i did. Once it's tested could be left out of the merge.

Once it's all good and ready to merge i'll create the example for the new instruction i created!

**Comment by balmy-gazebo** [comment]
Closed in PR from @L0STE
