### ISSUE TITLE
Remove supply and max supply on token group

### ISSUE THREAD

**Issue by kespinola** [wen-community/wen-new-standard#45]
### Background
The token group account currently has fields for max_supply and supply to track the number of assets belonging to the group as well as what it max supply could be.

### Issue
When adding an asset to a group the supply will increment but this requires the account to marked as mutable. In the case of heavy minting and adding to collection this will create a hot spot for the account where transactions queue up waiting to adjust the field. 

### Suggestion
Remove tracking supply and max_supply on token group. The supply should be derived from the members of the group and max supply can be managed by collection owner refusing to verify the asset or continue to mint.

**Comment by balmy-gazebo** [comment]
Good points, in the event a mint is very active, you'll still need some global confirmation that assets haven't passed the supply intended by the collection. Are you proposing not having any enforcement on collection size at the WNS level and collection sizes are determined by the authority? AKA a candy machine type program would be a common way to do this.

I'm not opposed to this, however the reason this was added is because this is the structure of Solana's TokenGroup account as is, so there will be limited flexibility at this point. I do not think it would be overly contentious though as you can still write to this account many times in a block without congestion issues. It's a good thing to be thinking about regardless

**Comment by kespinola** [comment]
@balmy-gazebo I know that this field was marked as deprecated in metaplex standard. Let me dig up the rational but I do think this is a spot to be wary of. 

Personally doing less in this early draft is likely the safest bet for avoiding performance bottlenecks and not occurring tech debt from simply having a limit set of functionality.

I've worked a lot with Metaplex collections and the main issue that should be addressed is considering the token group a unique account from a NFT. Having the collection NFT be another NFT is a nightmare when it comes to indexing because you don't know its a collection until you see a reference to the collection mint in later transactions.

Supply ideally is tracked off chain by indexers and again max_suppy enforced by the collection authority.

**Comment by balmy-gazebo** [comment]
Makes sense, check this here: https://github.com/solana-labs/solana-program-library/blob/c609163f6503f65f2b9e4e2a4dc24e0c15d91407/token-group/interface/src/state.rs#L15

Regardless once TokenGroup is in Prod the field will be there. But we could remove the convention of using this value as the standardized value for collection size. If you have an alternative I'd love to learn more.
