### ISSUE TITLE
More comprehensive test suite

### ISSUE THREAD

**Issue by balmy-gazebo** [wen-community/wen-new-standard#60]
The current test suite is all javascript based and limited in edge cases. Should try to support a more broad range of test cases and ideally add a rust library.

**Comment by kespinola** [comment]
Thanks @balmy-gazebo happy you opened this one. I'm looking at the test suite right now and am curious on the direction and what people want out of their test suite.

1. Overall what is the motivation behind the current spec setup vs leaning fully into the anchor test stack?
2. What are folks thoughts on ideal?

For me its:
- Running against local validator
- Use account snapshots to seed fixtures for the instruction under test instead of bootstrapping test state by replaying dependent instructions.
- Test suite written in rust. If possible use solana test bank to avoid running local validator.

**Comment by balmy-gazebo** [comment]
The original test suite was built like this to also test the SDK. I’m very open to moving to anchor tests for this. Do you have a repository in mind that does this well?

**Comment by kespinola** [comment]
> The original test suite was built like this to also test the SDK. I’m very open to moving to anchor tests for this. Do you have a repository in mind that does this well?

Doing research on that now.

Frens at nifty have a nice rust based setup using sdk generated by metaplex kinobi.

https://github.com/nifty-oss/asset/tree/main/clients/rust/asset

Then for vanilla anchor will mimic the examples in the anchor repo. They support some features like cloning accounts.

**Comment by kespinola** [comment]
https://github.com/wen-community/wen-new-standard/pull/74

New suite of tests have been written for both wns and royalty distribution including an example sales protocol for testing royalty enforcement.
